### ISSUE TITLE
[NEW] Create function to register colored ROI mask to histo + Stats in ROI

### ISSUE THREAD

**Issue by tanguyduval** [neuropoly/axonseg#17]
function as_reg_mask
function as_stats_mask_labeled
function as_stats_barplot

**Comment by alzaia** [comment]
Done
![screen shot 2015-11-05 at 10 32 29 am](https://cloud.githubusercontent.com/assets/14980394/10972764/9b41c270-83a8-11e5-9d1f-d14f9cc277bf.png)

**Comment by onarvaez** [comment]
Hello, I hope your day is going well.

I'm having some problems with:
 [indexes,mask_stats]=as_stats_mask_labeled_2(axonlist, mask_reg_labeled,PixelSize);
then:
**Index exceeds matrix dimensions.

Error in sortPoint2ContourCW (line 70)
diffY=diff(cat(1,y(1),y));

Error in mask2poly (line 120)
            [xCW,yCW]=sortPoint2ContourCW(maskContours(:,1),maskContours(:,2));
            
Error in as_stats_mask_labeled_2 (line 8)
    P=mask2poly(mask_reg_labeled==i,'Inner','CW');**

But I think that my problem is with "Registered mask" I don't know what to choose  with cursor in "figure 2" to obtain a correct "Labeled ROI" 
![5 2](https://user-images.githubusercontent.com/32722299/32147420-9edaf6f6-bcac-11e7-946a-cbcb02bc05ae.PNG)

Thanks

Greetings 
Biol. Omar Narvaez Delgado

**Comment by alzaia** [comment]
Hello, thanks for reaching out to us. Here are some tips that may help you : 

1) Are you currently using the last version of axonseg? (the current version is axonseg_3.0). If not, you can download it here: https://github.com/neuropoly/axonseg/releases/tag/v3.0.

2) To extract metrics based on ROIs, you can follow the following steps (also listed in the as_tutorial.m script):
- Register a multi-label mask on your segmented image with : 
[mask_reg_labeled, P_color]=as_reg_mask(mask,img);
* Before running this function, you have to load your axonlist (output of the segmentation) in the working space (your image, i.e. variable 'img' is inside axonlist). The 'mask' variable is your mask (image containing ROIs). 

Step 1 of this call: set corresponding points on mask and img (at least 3) to perform an affine registration. This should look like a GUI similar to this:
<img width="769" alt="1" src="https://user-images.githubusercontent.com/14980394/32148389-951fcdce-bccc-11e7-9bc5-f37ae8840169.PNG">
Step 2: when you are done with the registration, it will display the registered mask (figure 2). You have to select all the ROIs on the mask. With the cursor, click on each ROI. For the last ROI, use right click instead of left click to close the selection process. It should look like this:
<img width="446" alt="2" src="https://user-images.githubusercontent.com/14980394/32148409-e7b5b77e-bccc-11e7-82f4-aa74af42af63.PNG">
* Note that if you have display bugs in this step, you can comment lines 43-44 of as_reg_mask().

3) Call the following functions:
indexes=as_stats_mask_labeled(axonlist, mask_reg_labeled);
as_stats_barplot(axonlist,indexes,P_color);

Do not hesitate to reach out to us again if these tips do not solve your issue.

Have a good day,
Aldo

**Comment by onarvaez** [comment]
Thank you so much for your help. I've already completed the whole process correctly. My problem was in Step 2, in how I was clicking the registered mask (figure 2). 

Have a nice week 
Omar

**Comment by tanguyduval** [comment]
Just to clarify, the color mask with ROIS is created using any drawing software such as Gimp, powerpoint, keynote at any resolution.
We warp this mask (using `as_reg_mask`) to put it at the same resolution.

The important part is:
`indexes=as_stats_mask_labeled(axonlist, mask_reg_labeled);
as_stats_barplot(axonlist,indexes,P_color);
 `

NOTE: a similarity would have been a better option in most cases.
