### ISSUE TITLE
ManualCorrectionGUI Help

### ISSUE THREAD

**Issue by SegDaltonico** [neuropoly/axonseg#39]
Hi again,

Thanks for the help with my previous issue - I was able to successfully segment my entire image, and its looking good!

I am now trying to use the manualcorrectiongui, but I'm not exactly sure how. When I run ManualCorrectionGUI and try to open the axon segmenation image (named axonEquivDiameter_(axons)_0µm_3µm), I get the following error:

```
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software
OpenGL. For more information, click here. 
Error using adapthisteq
Expected input number 1, I, to be two-dimensional.

Error in adapthisteq>parseInputs (line 416)
validateattributes(I, {'uint8', 'uint16', 'double', 'int16', 'single'}, ...

Error in adapthisteq (line 155)
 noPadRect, distribution, alpha, int16ClassChange] = parseInputs(varargin{:});

Error in ManualCorrectionGUI>ManualCorrectionGUI_OpeningFcn (line 81)
handles.img=adapthisteq(handles.img);

Error in gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

Error in ManualCorrectionGUI (line 55)
    gui_mainfcn(gui_State, varargin{:});
```

**Comment by alzaia** [comment]
Hi, 

Normally, we dont develop the ManualCorrectionGUI anymore (mainly because there are tons of free software that allow to correct masks and do manual segmentation & that are better than what we proposed -> you can for example check out GIMP, its a free software for image processing and analysis). 

You can still use ManualCorrectionGUI if you want to. Here are the steps to do so:

1) You need your input grayscale image, but also a binary mask of the axons. In order to get the binary mask of the segmentation from AxonSeg, you can check the tutorial.m script. Basically, you have to create the mask by running these lines (you need the axonlist from the AxonSeg output): 

% Get the binary image of axon objects
bw_axonseg=as_display_label(axonlist,size(img),'axonEquivDiameter','axon');
img_BW_axons=im2bw(bw_axonseg,0);

You can then save img_BW_axons as a tif image (use imwrite(img_BW_axons,'mask.tif');).

2) You can then call the ManualCorrectionGUI.m function: 

ManualCorrectionGUI(path_img,path_mask);

Note the path_img is the path to your grayscale image and path_mask is the path to the mask you just created and saved from step 1.

3) Check the short demo here (make sure that your first step is to change the zoom, for example you can zoom to 1.5, or 2, or even x4): 
[manualcorrection_demo.zip](https://github.com/neuropoly/axonseg/files/903209/manualcorrection_demo.zip)

**Comment by tanguyduval** [comment]
Hi,

I did a small update so that should solve your bug. 
Please download and replace your ManualCorrectionGUI.m and ManualCorrectionGUI.fig files. New version can be found there: at https://github.com/neuropoly/axonseg/tree/master/code/GUI

But I agree if you have a big image or if you need to do many changes try other softwares!
Best,
Tanguy

**Comment by SegDaltonico** [comment]
Hey guys,

Thanks for the help! One other question: Once I've edited the mask using some other software, what's the best way to convert it back into the excel-type data file?

Best,
SegDaltonico

**Comment by alzaia** [comment]
What do you mean? So you added, corrected or removed axons from the mask, and now you want to redo the myelin segmentation with the new mask, and then get the new axonlist (with the metrics for each axon)? The Excel file is just a copy of the axonlist, in a table format.

**Comment by alzaia** [comment]
What do you mean? So you added, corrected or removed axons from the initial mask you got from AxonSeg, and now you have to relaunch the myelin segmentation, and then get your new axonlist (containing all the metrics for each axon and myelin), right? In fact, the Excel file is just a copy of the axonlist, but in a table format instead of a Matlab structure.

**Comment by SegDaltonico** [comment]
Yes, exactly.

**Comment by alzaia** [comment]
Hi SegDaltonico,

I'm working on a more complete documentation about this issue. I will inform you as soon as possible when it's ready. In the meantime, you can try using this method, as described by my colleague Tanguy : 

''
Hi SegDaltonico,

Let me complete my code.
````
img = imread('image.tif');
% if the myelin is black, inverse the contraste:
% img = imcomplement(img);
axonmask = imread('mask_axons.tif')
[axonlist, MyelinMask] = myelinInitialSegmention(img,axonmask);

% convert axonlist into excel file
axontable = struct2table(axonlist);
axontable.axonID=[];
axontable.data=[];
writetable(axontable);
````
A text file axontable.txt will be created. This file can be imported in excel.
Note that the units are Pixels here (not meters).

Thank you for your feedbacks,
Best,
Tanguy

''

Don't hesitate to give us your feedback. We're glad to help. :)

**Comment by SegDaltonico** [comment]
Hi,
Thank you again for the help. I've tried to turn my mask that I've edited with GIMP back into an axontable, but I've gotten a couple of errors using the myelinInitialSegmention() function. First, I got this error:

````
Loop over axons...   0%
Not enough input arguments.

Error in myelinInitialSegmention (line 211)
    axonlist(currentAxonLabel) =
    as_myelinseg2axonlist(currentMyelinBW,PixelSize);
 
211     axonlist(currentAxonLabel) = as_myelinseg2axonlist(currentMyelinBW,PixelSize);
````

I got this to go away by adding in an input request at the beginning for the pixel size in micrometers (which should work okay with the rest of the process, no?).

After I did this and tried running it again, however, I got the following error, which I'm stumped about:
````
Loop over axons...   4%
Error using  / 
Matrix dimensions must agree.

Error in myelinInitialSegmention (line 154)
    S1=S1/max(max(S1(S1<Inf)));
 
154     S1=S1/max(max(S1(S1<Inf)));
````

**Comment by alzaia** [comment]
Hello SegDaltonico, 

I tried to run the same code from my side (with an image and the corresponding axonal mask as inputs) to see if I can reproduce your error. In my case, it works without bugs. I think it may be possible that the GIMP output that you get after modifying the axonal mask is not in the right format. Here are some verification steps in order to hopefully identify the bug:

- make sure that the mask you generate from GIMP has the same size as the initial grayscale image
- make also sure that the GIMP output is a logical image (only 0s and 1s)

For instance, the inputs I used in my case were : 
- grayscale image: size 2212x3136 of type uint8 
- axonal mask: size 2212x3136 of type logical

You can verify the size and types of your images by loading them into the matlab workspace (use load() function or simply drag & drop the files into the workspace). If your inputs are not of the required type, you can convert them (use im2bw() to convert an image to logical --- for your axonal mask).

Tell me if it resolves your bug.

Have a nice day, 
Aldo

**Comment by SegDaltonico** [comment]
Hi Alzaia,

You're right, my mask image was still in grayscale even though it was all black and white, so I changed it to a logical.
So now:
My grayscale image size is 1536x2048 uint8,
and my axonal mask image is a 1536X2048 logical.

But - I've gotten the same error again, only this time it got to 99% before it came up:

````
Loop over axons...  99%
Error using  / 
Matrix dimensions must agree.

Error in myelinInitialSegmention (line 154)
    S1=S1/max(max(S1(S1<Inf)));
 
154     S1=S1/max(max(S1(S1<Inf)));
````

**Comment by alzaia** [comment]
Does it work if you put lines 152 to 155 of myelinInitialSegmention() in comments?

%     S1=S1+S2_reg; S2=S2+S1_reg;
%     
%     S1=S1/max(max(S1(S1<Inf)));
%     S2=S2/max(max(S2(S2<Inf)));

**Comment by tanguyduval** [comment]
Hi SegDaltonico,

It's possible that some manually​ segmented axons lead to errors. I suspect an axon in your mask is touching the border of the image, or present a strange shape, or consists of too few voxels. 

Could you please share with us this particular dataset so that we can reproduce the error.
You can send us the image + axon mask to neuropolylab@gmail.com

Note that we might have solved this issue. I recommend to update to the most recent version of AxonSeg and try again. 

Best,
Tanguy

**Comment by SegDaltonico** [comment]
Hi guys,

Sorry for the delay in replying - other things have been keeping me pretty busy the past few weeks. Alzaia, I tried your solution and it worked. Do I lose out on anything by getting rid of those lines, or should I be okay? Thanks again for the help!

Best,
SegDaltonico

**Comment by alzaia** [comment]
Hello SegDaltonico,

Does it look to work fine without these lines? I also tried without the lines when you first asked me, I didnt have any problem. 

Also, did you try the last version of AxonSeg? This could have been a problem in one of the older releases.

**Comment by alzaia** [comment]
Hello SegDaltonico,

Does it look to work fine without these lines? I also tried without the lines when you first asked me, I didnt have any problem. So it should be ok.

Also, did you try the last version of AxonSeg? This could have been a problem in one of the older releases.

Thanks for the interest,

Aldo

**Comment by alzaia** [comment]
Hello SegDaltonico,

Does it look to work fine without these lines? I also tried without the lines, it seemed to work fine. So it should be ok without the lines.

Also, did you try the last version of AxonSeg? This could have been a problem in one of the older releases.

Thanks for the interest,

Aldo

**Comment by alzaia** [comment]
Hello SegDaltonico, 

In fact, these lines force outer boundary to be outer. However, in practice, these lines are probably useless. I tried on 2 test images and the Dice between the segmentations with or without these lines was 100% (same results between the 2).  This was tested on only few samples, so I cannot guarantee similar results in all cases. Don't hesitate to send us your datasets, we will be glad to correct the bug.
