### ISSUE TITLE
Maximum diameter

### ISSUE THREAD

**Issue by lconcha** [neuropoly/axonseg#40]
Hello.

I am truly impressed by the quality of axon/myelin segmentation provided by AxonSeg. Great work!

While AxonSeg does a good job most of the times, sometimes capillaries and glial cell nuclei can be mistakenly labelled as axons. At first glance it is obvious that this non-axonal structures are much larger in diameter. I see that a minimum diameter can be defined, but I cannot figure out if there is a max_diameter setting. So far I just delete such axons after segmentation, but I  wanted to check if you can think of a better option so that they are not labelled in the first place.

Thanks for all the hard work!

**Comment by tanguyduval** [comment]
Hi,

Thank you for your positive feedback.
We correct these errors after segmentation. 
Please use the following commands in Matlab:
````
load axonlist.mat
% remove axons larger than 10µm
axonlist([axonlist.axonEquivDiameter]>10)=[];
% save the image
as_display_label(axonlist,size(img),'axonEquivDiameter','axon',img);
% convert axonlist into excel file
axontable = struct2table(axonlist);
axontable.axonID=[];
axontable.data=[];
writetable(axontable);
````
A text file axontable.txt will be created. This file can be imported in excel.
Note that the units are Pixels here (not meters).

Thank you for your feedbacks,
Best,
Tanguy

**Comment by alzaia** [comment]
Hello Luis,

Thanks for the nice words. We are happy to help.

Your comment is very relevant. In fact, as you can see in our paper, we explored different parameters in order to have the better discrimination between false and true axons. It turns out that most of the false axons were small residues or extended shapes between 2 or more axons. That's mainly the reason why we focused on setting the minimal size, the solidity and the ellipticity. 

As Tanguy said above, you can correct the output axonlist depending of your needs. You can filter by axon size, or by any other metric available in the axonlist structure.

**Comment by lconcha** [comment]
Excellent. It seems like what I was doing was on the right path. I appreciate the help.
