### ISSUE TITLE
One "SegParameters" for two different sets of images

### ISSUE THREAD

**Issue by onarvaez** [neuropoly/axonseg#48]
Hello, I hope your day is doing well.

First of all I want to thank you for the great work on AxonSeg.

I have a question. I'm working with two sets of images, one with intact axons and another one with degenerated axons. I found the optimal "SegParameters.mat" for each set of images (SegParameters_intact and SegParameters_degenerated respectively), but I want to achieve the same results that I obtain in each set but just with one SegParameters archive.

I've already tried to use several parameters, modifying and training the DA, and systematically changing every value with no really close results. If I use strict values for the degenerated ones, those parameters are restrictive for the intact ones and vice versa. In that search I found parameters (SegParameters_both) that show close values for each set but still overestimating in degenerated axons images and underestimating in the intact ones. For example, for the images that I send you I obtained this: 

                                                     Intact_axons_average (1_intact.jpg)
SegParameters_intact -                         3302 (Optimal)
SegParameters_degenerated -             2738
SegParameters_both -                          3049

                                                 Degenerated_axons_average (1_degenerated.jpg)
SegParameters_intact -                         656
SegParameters_degenerated -             388 (Optimal)
SegParameters_both -                           532

So, I was wondering if are there some values that I missing in "SegParameters_both" that allows me to increase that margin for intact axons and decrease it for degenerated ones?

Here are the SegParameters that I used
https://www.dropbox.com/sh/mrluzmlrbkyv5il/AABnBwU6Y3FPsL--7HCgvETJa?dl=0  

Thank you so much for your time. 

Greetings

Biol. Omar Narvaez
Instituto de Neurobiología, UNAM 

![1_degenerated](https://user-images.githubusercontent.com/32722299/33393066-869ab5b2-d503-11e7-95ef-52f3b9dfc7db.jpg)

![1_intact](https://user-images.githubusercontent.com/32722299/33393057-7e09f390-d503-11e7-84bd-ea1d6b50e9d0.jpg)

**Comment by alzaia** [comment]
Hello,

This is a common issue when having very different samples in terms of size, shape, intensity of axons. It is not easy to find segmentation parameters that will work on all types of images (in your case, healthy vs degenerate nerve fibers).

Here are 3 things you could try:

1) Stitch your 2 images (or parts of your images) in one single image in order to explore the segmentation parameters with the GUI on both types (intact and degenerate) at the same time. It will be easier to see which parameters work on both types of images.

2) You could apply both SegParameters.mat (the one optimized for intact axons, and the other optimized for degenerate ones) on both images. So you will get, for each image, 2 outputs (one for each SegParam). And then you could merge both outputs. We just pushed an option in the code in order to segment only axons (download the last version on GitHub). 

For instance, you could use the following script:
```
segParam1.skipmyelin = true;
axon_mask1=as_Segmentation(im_in,segParam1);
segParam2.skipmyelin = true;
axon_mask2=as_Segmentation(im_in,segParam2);

axon_mask_final = axon_mask1 | axon_mask2;
```


And then, when your merged axon segmentation looks fine, you can launch the myelin segmentation (as explained in the tutorial.m script).

3) Last option if there are still some false positives or false negatives: you could manually correct the axon masks (with our GUI, named ManualCorrectionGUI.m, or with a free software such as GIMP). And then, you can launch the myelin segmentation on the corrected masks.

Best, 

Aldo

**Comment by jcohenadad** [comment]
@alzaia: how about training a specific model in AxonDeepSeg? Don't you think that could be more efficient in this case? Especially if @onarvaez has a lot of similarly-looking data to process.

**Comment by alzaia** [comment]
I thought about it, but in this case, the 2 types of images (healthy vs degenerated) are very different in terms of content, so I doubt we would be able to train a single model working well on both types. 

@onarvaez , how large is your dataset?

**Comment by jcohenadad** [comment]
i meant two models, one for each condition

**Comment by alzaia** [comment]
Yeah, but that does not resolve his issue, which is to have a single model for both images. He already has a model optimized for each type in AxonSeg.

**Comment by onarvaez** [comment]
Thank you so much for your answers and suggestions.
I've tried your suggestions already and related to the first one, it shows similar results to an average SegParameters, overestimating and underestimating. 
Merging boths outputs it's a good option but it seems that manual correction makes more acurate results in every case. My dataset by now are about 300 images (150 degenerated and 150 intact) but in the next months im going to have much more, probably some of the degenerated ones not like what I have now, and in that case it should be working good just with a SegParameter. The thing is that it would be great if one SegParameter works good in both in all dataset to be able to say that the differences what we see (even that in this case are evident) are only by the injury model and not because we are more restrictive in the parameters used or manual-corrected in degenerated ones.
 And I'm sorry but what do you mean with axon/myelin labels? The resulted images or masks?    

And again, thank you for your time.

**Comment by alzaia** [comment]
I totally understand your point. What I would suggest is to manually segment a few images from both types (intact and degenerated), and then validate the AxonSeg segmentation on them by computing for example the Dice similarity coefficient, the sensitivity and the precision. Note that we have a function that does that (as_validation.m). The objective of this would be to show that the SegParameters that you use for each type of image give results comparable to the corresponding ground truth labels.

Best,
Aldo

**Comment by onarvaez** [comment]
Alright, I'm going to do that and see how it goes. 
I will keep you updated, thank you.

Greetings. 
Omar N.

**Comment by tanguyduval** [comment]
We answered user issue. Unfortunately, this is a general issue of all segmentation software, the performance depends on the contrast and the image appearance. 
The only solution: build a perfect segmentation model. [AxonDeepSeg project](https://github.com/neuropoly/axondeepseg) is working on that :)
